### ISSUE TITLE
Android Maven

### ISSUE THREAD

**Issue by j-cheung** [Notificare/notificare-sdk-react-native#5]
Hi

trying to implement this on Android.

added the following to build.gradle

buildscript repositories
```
        maven { url 'https://maven.notifica.re/releases' }
        maven { url 'https://developer.huawei.com/repo' }
```

allprojects repositories
```
        maven { url 'https://maven.notifica.re/releases' }
        maven { url 'https://maven.notifica.re/prereleases' }
        maven { url 'https://developer.huawei.com/repo' }
```

getting errors Received status code 403 from server: Forbidden

trying to access https://maven.notifica.re/ on browser also shows forbidden 

thanks.

**Comment by hpinhal** [comment]
Hi @j-cheung,

It seems something is not well configured in your `build.gradle` files.
You can take a look at the [sample](https://github.com/Notificare/notificare-sdk-react-native/tree/main/packages/sample/android) hosted on this repo.

About the browser showing forbidden, that is by design. We do not provide a maven repo explorer.

**Comment by hpinhal** [comment]
Hi @j-cheung,

Due to our maven repo resolution, we respond with a 403, hence showing that error under our repo.
However, not everything has been moved from jcenter to other maven repos. Since you commented out jcenter, Gradle can't resolve that dependency, causing the error.
